spring:
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
      username: kuma
      password: xj675613722
mybatis:
  configuration:
#    启用驼峰转换
    map-underscore-to-camel-case: true
  mapper-locations: classpath:Mybatis/Mappers/*.xml
  type-aliases-package: cqut.blogspring.pojo
server:
  port: 8085
